--------------------------------------------------------
--  File created - วันจันทร์-มีนาคม-09-2569   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BILL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."BILL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BOOKER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."BOOKER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BOOKING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."BOOKING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CONTRACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."CONTRACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."PAYMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROOM" 
   (	"RPRICE" NUMBER(10,2), 
	"RTYPE" VARCHAR2(50 BYTE), 
	"RFLOOR" NUMBER, 
	"RDETAILS" VARCHAR2(255 BYTE), 
	"RSTATUS" VARCHAR2(20 BYTE), 
	"ROOMID" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PAYMENT" 
   (	"PAYSTATUS" VARCHAR2(20 BYTE), 
	"PAYID" NUMBER, 
	"PAYDATE" DATE, 
	"PAYAMOUNT" NUMBER(10,2), 
	"ROOMID" VARCHAR2(5 BYTE), 
	"BILLID" NUMBER DEFAULT NULL, 
	"ACCID" NUMBER, 
	"BOOKINGID" NUMBER, 
	"BOOKERID" NUMBER, 
	"PAYFILES" VARCHAR2(255 BYTE), 
	"PAYTYPE" VARCHAR2(20 BYTE) DEFAULT 'RENT'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBER" 
   (	"MEMNAME" VARCHAR2(100 BYTE), 
	"MEMPHONE" VARCHAR2(15 BYTE), 
	"MEMEMAIL" VARCHAR2(100 BYTE), 
	"ACCID" NUMBER, 
	"ROOMID" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRACT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONTRACT" 
   (	"CONTRACID" NUMBER, 
	"CONTRACTFILE" VARCHAR2(500 BYTE), 
	"ROOMID" VARCHAR2(10 BYTE), 
	"UPLOADDATE" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOKING" 
   (	"BOOKINGID" NUMBER, 
	"BKSTATUS" VARCHAR2(20 BYTE), 
	"BKDATE" DATE, 
	"BOOKERID" NUMBER, 
	"ROOMID" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOKER" 
   (	"BOOKERID" NUMBER, 
	"BNAME" VARCHAR2(100 BYTE), 
	"BPHONE" VARCHAR2(15 BYTE), 
	"BEMAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BILL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BILL" 
   (	"BILLID" NUMBER, 
	"WATERUNIT" NUMBER(10,2), 
	"ELECTRICUNIT" NUMBER(10,2), 
	"WATERCOST" NUMBER(10,2), 
	"ELECTRICCOST" NUMBER(10,2), 
	"TOTALAMOUNT" NUMBER(10,2), 
	"ACCID" NUMBER, 
	"ROOMID" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'UNPAID', 
	"BILLMONTH" VARCHAR2(100 BYTE), 
	"BILLYEAR" NUMBER, 
	"DUEDATE" DATE, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"ADMINUSER" VARCHAR2(50 BYTE), 
	"ADMINPASS" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACCOUNT" 
   (	"ACCID" NUMBER, 
	"ACCUSER" VARCHAR2(50 BYTE), 
	"ACCPASS" VARCHAR2(100 BYTE), 
	"ROOMID" VARCHAR2(5 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"DELETED_AT" DATE DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ACCOUNT"."IS_ACTIVE" IS '1 = ใช้งานอยู่, 0 = ปิดใช้งาน (Soft Delete)';
   COMMENT ON COLUMN "SYSTEM"."ACCOUNT"."DELETED_AT" IS 'วันที่ Deactivate Account';
REM INSERTING into SYSTEM.ROOM
SET DEFINE OFF;
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',1,'-','AVAILABLE','A1');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',1,'-','AVAILABLE','A2');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',1,'-','AVAILABLE','A3');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',1,'-','AVAILABLE','A4');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3200,'Standard',1,'Corner room','AVAILABLE','A5');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',2,'-','AVAILABLE','B1');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',2,'-','AVAILABLE','B2');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',2,'-','AVAILABLE','B3');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3000,'Standard',2,'-','AVAILABLE','B4');
Insert into SYSTEM.ROOM (RPRICE,RTYPE,RFLOOR,RDETAILS,RSTATUS,ROOMID) values (3200,'Standard',2,'Corner room','AVAILABLE','B5');
REM INSERTING into SYSTEM.PAYMENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.MEMBER
SET DEFINE OFF;
REM INSERTING into SYSTEM.CONTRACT
SET DEFINE OFF;
REM INSERTING into SYSTEM.BOOKING
SET DEFINE OFF;
REM INSERTING into SYSTEM.BOOKER
SET DEFINE OFF;
REM INSERTING into SYSTEM.BILL
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADMIN
SET DEFINE OFF;
Insert into SYSTEM.ADMIN (ADMINUSER,ADMINPASS) values ('admin','1234');
REM INSERTING into SYSTEM.ACCOUNT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ROOM" ON "SYSTEM"."ROOM" ("ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKPAYMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKPAYMENT" ON "SYSTEM"."PAYMENT" ("PAYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKMEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKMEMBER" ON "SYSTEM"."MEMBER" ("ACCID", "ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKCONTRACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKCONTRACT" ON "SYSTEM"."CONTRACT" ("CONTRACID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKBOOKING
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKBOOKING" ON "SYSTEM"."BOOKING" ("BOOKINGID", "BOOKERID", "ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKBOOKER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKBOOKER" ON "SYSTEM"."BOOKER" ("BOOKERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKBILL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKBILL" ON "SYSTEM"."BILL" ("BILLID", "ACCID", "ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_ACCOUNT_ACTIVE
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_ACCOUNT_ACTIVE" ON "SYSTEM"."ACCOUNT" ("IS_ACTIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index XPKACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."XPKACCOUNT" ON "SYSTEM"."ACCOUNT" ("ACCID", "ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY ("ROOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("PAYID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" MODIFY ("PAYTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAYMENT" ADD CONSTRAINT "XPKPAYMENT" PRIMARY KEY ("PAYID")
  USING INDEX "SYSTEM"."XPKPAYMENT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("ACCID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" ADD CONSTRAINT "XPKMEMBER" PRIMARY KEY ("ACCID", "ROOMID")
  USING INDEX "SYSTEM"."XPKMEMBER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTRACT" MODIFY ("CONTRACID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTRACT" ADD CONSTRAINT "XPKCONTRACT" PRIMARY KEY ("CONTRACID")
  USING INDEX "SYSTEM"."XPKCONTRACT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKING" MODIFY ("BOOKINGID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOKING" MODIFY ("BOOKERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOKING" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOKING" ADD CONSTRAINT "XPKBOOKING" PRIMARY KEY ("BOOKINGID", "BOOKERID", "ROOMID")
  USING INDEX "SYSTEM"."XPKBOOKING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKER" MODIFY ("BOOKERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOKER" ADD CONSTRAINT "XPKBOOKER" PRIMARY KEY ("BOOKERID")
  USING INDEX "SYSTEM"."XPKBOOKER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BILL" MODIFY ("BILLID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BILL" MODIFY ("ACCID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BILL" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BILL" ADD CONSTRAINT "XPKBILL" PRIMARY KEY ("BILLID", "ACCID", "ROOMID")
  USING INDEX "SYSTEM"."XPKBILL"  ENABLE;
  ALTER TABLE "SYSTEM"."BILL" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACCOUNT" MODIFY ("ACCID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCOUNT" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "XPKACCOUNT" PRIMARY KEY ("ACCID", "ROOMID")
  USING INDEX "SYSTEM"."XPKACCOUNT"  ENABLE;
  ALTER TABLE "SYSTEM"."ACCOUNT" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAYMENT" ADD CONSTRAINT "R_32" FOREIGN KEY ("ROOMID")
	  REFERENCES "SYSTEM"."ROOM" ("ROOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBER" ADD CONSTRAINT "R_2" FOREIGN KEY ("ROOMID")
	  REFERENCES "SYSTEM"."ROOM" ("ROOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKING" ADD CONSTRAINT "R_12" FOREIGN KEY ("ROOMID")
	  REFERENCES "SYSTEM"."ROOM" ("ROOMID") ENABLE;
  ALTER TABLE "SYSTEM"."BOOKING" ADD CONSTRAINT "R_4" FOREIGN KEY ("BOOKERID")
	  REFERENCES "SYSTEM"."BOOKER" ("BOOKERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BILL" ADD CONSTRAINT "R_17" FOREIGN KEY ("ROOMID")
	  REFERENCES "SYSTEM"."ROOM" ("ROOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "R_15" FOREIGN KEY ("ROOMID")
	  REFERENCES "SYSTEM"."ROOM" ("ROOMID") ENABLE;
