-- SQLite Schema for Apartment DBMS

-- 1. ROOM Table
CREATE TABLE IF NOT EXISTS ROOM (
    ROOMID VARCHAR(5) PRIMARY KEY,
    RPRICE REAL,
    RTYPE VARCHAR(50),
    RFLOOR INTEGER,
    RDETAILS TEXT,
    RSTATUS VARCHAR(20) DEFAULT 'AVAILABLE'
);

-- 2. BOOKER Table
CREATE TABLE IF NOT EXISTS BOOKER (
    BOOKERID INTEGER PRIMARY KEY AUTOINCREMENT,
    BNAME VARCHAR(100),
    BPHONE VARCHAR(15),
    BEMAIL VARCHAR(100)
);

-- 3. BOOKING Table
CREATE TABLE IF NOT EXISTS BOOKING (
    BOOKINGID INTEGER PRIMARY KEY AUTOINCREMENT,
    BKSTATUS VARCHAR(20),
    BKDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    BOOKERID INTEGER,
    ROOMID VARCHAR(5),
    FOREIGN KEY (BOOKERID) REFERENCES BOOKER(BOOKERID),
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- 4. ACCOUNT Table
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCUSER VARCHAR(50) UNIQUE,
    ACCPASS VARCHAR(100),
    ROOMID VARCHAR(5),
    IS_ACTIVE INTEGER DEFAULT 1, -- 1 = active, 0 = inactive
    DELETED_AT DATETIME,
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- 5. MEMBER Table
CREATE TABLE IF NOT EXISTS MEMBER (
    MEMID INTEGER PRIMARY KEY AUTOINCREMENT,
    MEMNAME VARCHAR(100),
    MEMPHONE VARCHAR(15),
    MEMEMAIL VARCHAR(100),
    ACCID INTEGER,
    ROOMID VARCHAR(5),
    FOREIGN KEY (ACCID) REFERENCES ACCOUNT(ACCID),
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- 6. BILL Table
CREATE TABLE IF NOT EXISTS BILL (
    BILLID INTEGER PRIMARY KEY AUTOINCREMENT,
    WATERUNIT REAL,
    ELECTRICUNIT REAL,
    WATERCOST REAL,
    ELECTRICCOST REAL,
    TOTALAMOUNT REAL,
    ACCID INTEGER,
    ROOMID VARCHAR(5),
    STATUS VARCHAR(20) DEFAULT 'UNPAID',
    BILLMONTH VARCHAR(20),
    BILLYEAR INTEGER,
    DUEDATE DATETIME,
    IS_DELETED INTEGER DEFAULT 0,
    FOREIGN KEY (ACCID) REFERENCES ACCOUNT(ACCID),
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- 7. PAYMENT Table
CREATE TABLE IF NOT EXISTS PAYMENT (
    PAYID INTEGER PRIMARY KEY AUTOINCREMENT,
    PAYSTATUS VARCHAR(20),
    PAYDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PAYAMOUNT REAL,
    ROOMID VARCHAR(5),
    BILLID INTEGER,
    ACCID INTEGER,
    BOOKINGID INTEGER,
    BOOKERID INTEGER,
    PAYFILES VARCHAR(255),
    PAYTYPE VARCHAR(20) DEFAULT 'RENT',
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID),
    FOREIGN KEY (BILLID) REFERENCES BILL(BILLID),
    FOREIGN KEY (ACCID) REFERENCES ACCOUNT(ACCID),
    FOREIGN KEY (BOOKINGID) REFERENCES BOOKING(BOOKINGID),
    FOREIGN KEY (BOOKERID) REFERENCES BOOKER(BOOKERID)
);

-- 8. CONTRACT Table
CREATE TABLE IF NOT EXISTS CONTRACT (
    CONTRACID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONTRACTFILE VARCHAR(500),
    ROOMID VARCHAR(10),
    UPLOADDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- 9. ADMIN Table
CREATE TABLE IF NOT EXISTS ADMIN (
    ADMINUSER VARCHAR(50) PRIMARY KEY,
    ADMINPASS VARCHAR(100)
);

-- Seed Data
-- Rooms
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('A1', 3000, 'Standard', 1, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('A2', 3000, 'Standard', 1, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('A3', 3000, 'Standard', 1, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('A4', 3000, 'Standard', 1, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('A5', 3200, 'Standard', 1, 'Corner room', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('B1', 3000, 'Standard', 2, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('B2', 3000, 'Standard', 2, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('B3', 3000, 'Standard', 2, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('B4', 3000, 'Standard', 2, '-', 'AVAILABLE');
INSERT OR IGNORE INTO ROOM (ROOMID, RPRICE, RTYPE, RFLOOR, RDETAILS, RSTATUS) VALUES ('B5', 3200, 'Standard', 2, 'Corner room', 'AVAILABLE');

-- Admin
INSERT OR IGNORE INTO ADMIN (ADMINUSER, ADMINPASS) VALUES ('admin', '1234');
